// app/layout.js
import Sidebar from "../components/admin/sidebar";
import "../styles/admin/layout.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="layout-body">
          <Sidebar/>
          <div className="layout-main">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
