// DummyDataSearch.js

export const alumniData = [
  {
    id: "1",
    first_name: "Alice",
    middle_name: "J",
    last_name: "Smith",
    email: "alice.smith@example.com",
    image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    student_num: "2018-00001",
    year_graduated: "2022-06-15T00:00:00.000Z",
    location: "San Francisco, CA",
    skills: "JavaScript, React, Node.js",
    interests: "Web Development, UI/UX Design",
    honorifics: "Ms.",
    gender: "Female",
    birthdate: "1999-05-20",
    citizenship: "USA",
    civil_status: "Single",
    degree_program: "BS Computer Science",
    experience: [
      {
        company: "Tech Solutions Inc.",
        location: "San Francisco, CA",
        position: "Frontend Developer",
        start_date: "2022-07-01",
        end_date: null,
      },
    ],
    affiliations: [
      {
        organization: "ACM Women in Computing",
        position: "Member",
        start_date: "2020-09-01",
        end_date: null,
        institution: "University of California, Berkeley",
      },
    ],
  },
  {
    id: "2",
    first_name: "Bob",
    middle_name: "",
    last_name: "Johnson",
    email: "bob.johnson@example.com",
    image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    student_num: "2017-00015",
    year_graduated: "2021-07-20T00:00:00.000Z",
    location: "New York, NY",
    skills: "Python, Data Analysis, Machine Learning",
    interests: "Artificial Intelligence, Data Science",
    honorifics: "Mr.",
    gender: "Male",
    birthdate: "1998-11-03",
    citizenship: "USA",
    civil_status: "Married",
    degree_program: "MS Data Science",
    experience: [
      {
        company: "Data Insights Corp.",
        location: "New York, NY",
        position: "Data Scientist",
        start_date: "2021-08-15",
        end_date: null,
      },
    ],
    affiliations: [
      {
        organization: "IEEE Computational Intelligence Society",
        position: "Student Member",
        start_date: "2019-10-01",
        end_date: "2021-07-20",
        institution: "Columbia University",
      },
    ],
  },
  {
    id: "3",
    first_name: "Charlie",
    middle_name: "B",
    last_name: "Williams",
    email: "charlie.williams@example.com",
    image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    student_num: "2019-00100",
    year_graduated: "2023-05-10T00:00:00.000Z",
    location: "Seattle, WA",
    skills: "C++, Game Development, Unity",
    interests: "Game Design, Virtual Reality",
    honorifics: "Mr.",
    gender: "Male",
    birthdate: "2000-01-15",
    citizenship: "USA",
    civil_status: "Single",
    degree_program: "BS Game Development",
    experience: [
      {
        company: "Indie Game Studio",
        location: "Seattle, WA",
        position: "Junior Game Developer",
        start_date: "2023-06-01",
        end_date: null,
      },
    ],
    affiliations: [
      {
        organization: "IGDA (International Game Developers Association)",
        position: "Member",
        start_date: "2022-03-01",
        end_date: null,
        institution: "University of Washington",
      },
    ],
  },
  {
    id: "4",
    first_name: "Diana",
    middle_name: "L",
    last_name: "Brown",
    email: "diana.brown@example.com",
    image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    student_num: "2016-00050",
    year_graduated: "2020-08-25T00:00:00.000Z",
    location: "Los Angeles, CA",
    skills: "Java, Android Development, Firebase",
    interests: "Mobile App Development, Cloud Computing",
    honorifics: "Mrs.",
    gender: "Female",
    birthdate: "1997-07-01",
    citizenship: "USA",
    civil_status: "Divorced",
    degree_program: "BS Computer Engineering",
    experience: [
      {
        company: "Mobile Innovations Inc.",
        location: "Los Angeles, CA",
        position: "Android Developer",
        start_date: "2020-09-15",
        end_date: null,
      },
    ],
    affiliations: [
      {
        organization: "Society of Women Engineers (SWE)",
        position: "Member",
        start_date: "2018-09-01",
        end_date: null,
        institution: "University of Southern California",
      },
    ],
  },
  {
    id: "5",
    first_name: "Ethan",
    middle_name: "",
    last_name: "Davis",
    email: "ethan.davis@example.com",
    image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    student_num: "2020-00200",
    year_graduated: "2024-06-30T00:00:00.000Z",
    location: "Chicago, IL",
    skills: "SQL, Database Management, Business Intelligence",
    interests: "Data Warehousing, Business Analytics",
    honorifics: "Mr.",
    gender: "Male",
    birthdate: "2001-03-10",
    citizenship: "USA",
    civil_status: "Single",
    degree_program: "BS Business Analytics",
    experience: [
      {
        company: "Analytics Solutions Group",
        location: "Chicago, IL",
        position: "Data Analyst",
        start_date: "2024-07-15",
        end_date: null,
      },
    ],
    affiliations: [
      {
        organization: "INFORMS (Institute for Operations Research and the Management Sciences)",
        position: "Student Chapter Member",
        start_date: "2022-10-01",
        end_date: "2024-06-30",
        institution: "University of Chicago",
      },
    ],
  },
  {
    id: "6",
    first_name: "Fiona",
    middle_name: "S",
    last_name: "Miller",
    email: "fiona.miller@example.com",
    image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    student_num: "2015-00075",
    year_graduated: "2019-09-05T00:00:00.000Z",
    location: "Austin, TX",
    skills: "HTML, CSS, UI/UX Design",
    interests: "Frontend Development, Web Accessibility",
    honorifics: "Ms.",
    gender: "Female",
    birthdate: "1996-12-25",
    citizenship: "USA",
    civil_status: "Single",
    degree_program: "BA Digital Arts and Sciences",
    experience: [
      {
        company: "Web Design Agency",
        location: "Austin, TX",
        position: "UI/UX Designer",
        start_date: "2019-10-01",
        end_date: null,
      },
    ],
    affiliations: [
      {
        organization: "AIGA (the professional association for design)",
        position: "Member",
        start_date: "2017-09-01",
        end_date: null,
        institution: "University of Texas at Austin",
      },
    ],
  },
  {
    id: "7",
    first_name: "George",
    middle_name: "R",
    last_name: "Wilson",
    email: "george.wilson@example.com",
    image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    student_num: "2021-00300",
    year_graduated: "2025-05-01T00:00:00.000Z",
    location: "Boston, MA",
    skills: "C#, .NET, ASP.NET",
    interests: "Backend Development, Software Architecture",
    honorifics: "Mr.",
    gender: "Male",
    birthdate: "2002-08-18",
    citizenship: "USA",
    civil_status: "Single",
    degree_program: "BS Software Engineering",
    experience: [
      {
        company: "Software Innovations Corp.",
        location: "Boston, MA",
        position: "Backend Developer Intern",
        start_date: "2024-06-01",
        end_date: "2025-04-30",
      },
    ],
    affiliations: [
      {
        organization: ".NET Foundation",
        position: "Community Member",
        start_date: "2023-01-01",
        end_date: null,
        institution: "Massachusetts Institute of Technology",
      },
    ],
  },
  {
    id: "8",
    first_name: "Hannah",
    middle_name: "",
    last_name: "Moore",
    email: "hannah.moore@example.com",
    image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    student_num: "2014-00120",
    year_graduated: "2018-07-15T00:00:00.000Z",
    location: "Denver, CO",
    skills: "Ruby, Ruby on Rails, PostgreSQL",
    interests: "Full-stack Development, Agile Methodologies",
    honorifics: "Mrs.",
    gender: "Female",
    birthdate: "1995-04-02",
    citizenship: "USA",
    civil_status: "Married",
    degree_program: "BS Computer Science",
    experience: [
      {
        company: "Agile Software Solutions",
        location: "Denver, CO",
        position: "Full-stack Developer",
        start_date: "2018-08-01",
        end_date: null,
      },
    ],
    affiliations: [
      {
        organization: "Rails Girls",
        position: "Mentor",
        start_date: "2019-03-01",
        end_date: null,
        institution: "University of Colorado Boulder",
      },
    ],
  },
  {
    id: "9",
    first_name: "Ivy",
    middle_name: "P",
    last_name: "Taylor",
    email: "ivy.taylor@example.com",
    image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    student_num: "2022-00400",
    year_graduated: "2026-06-10T00:00:00.000Z",
    location: "Miami, FL",
    skills: "PHP, Laravel, MySQL",
    interests: "Web Development, E-commerce Solutions",
    honorifics: "Ms.",
    gender: "Female",
    birthdate: "2003-09-22",
    citizenship: "USA",
    civil_status: "Single",
    degree_program: "BS Information Technology",
    experience: [
      {
        company: "E-commerce Platforms Inc.",
        location: "Miami, FL",
        position: "Web Developer Intern",
        start_date: "2025-07-01",
        end_date: null,
      },
    ],
    affiliations: [
      {
        organization: "PHP Miami",
        position: "Member",
        start_date: "2024-01-01",
        end_date: null,
        institution: "Florida International University",
      },
    ],
  },
  {
    id: "10",
    first_name: "Jack",
    middle_name: "",
    last_name: "Anderson",
    email: "jack.anderson@example.com",
    image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    student_num: "2013-00150",
    year_graduated: "2017-08-20T00:00:00.000Z",
    location: "Philadelphia, PA",
    skills: "Swift, iOS Development, Xcode",
    interests: "Mobile App Development, Apple Ecosystem",
    honorifics: "Mr.",
    gender: "Male",
    birthdate: "1994-06-05",
    citizenship: "USA",
    civil_status: "Single",
    degree_program: "BS Software Engineering",
    experience: [
      {
        company: "Apple Mobile Apps",
        location: "Philadelphia, PA",
        position: "iOS Developer",
        start_date: "2017-09-01",
        end_date: null,
      },
    ],
    affiliations: [
      {
        organization: "CocoaHeads Philly",
        position: "Organizer",
        start_date: "2019-05-01",
        end_date: null,
        institution: "University of Pennsylvania",
      },
    ],
  },
  {
    id: "11",
    first_name: "Kelly",
    middle_name: "M",
    last_name: "Thomas",
    email: "kelly.thomas@example.com",
    image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    student_num: "2019-00250",
    year_graduated: "2023-07-01T00:00:00.000Z",
    location: "Atlanta, GA",
    skills: "TypeScript, Angular, NestJS",
    interests: "Frontend Development, Backend Development",
    honorifics: "Ms.",
    gender: "Female",
    birthdate: "2000-11-12",
    citizenship: "USA",
    civil_status: "Single",
    degree_program: "BS Computer Science",
    experience: [
      {
        company: "Full-Stack Technologies",
        location: "Atlanta, GA",
        position: "Software Engineer",
        start_date: "2023-08-15",
        end_date: null,
      },
    ],
    affiliations: [
      {
        organization: "Women Who Code Atlanta",
        position: "Member",
        start_date: "2021-02-01",
        end_date: null,
        institution: "Georgia Institute of Technology",
      },
    ],
  },
  {
    id: "12",
    first_name: "Liam",
    middle_name: "",
    last_name: "Jackson",
    email: "liam.jackson@example.com",
    image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
    student_num: "2016-00180",
    year_graduated: "2020-09-15T00:00:00.000Z",
    location: "Dallas, TX",
    skills: "Go, Docker, Kubernetes",
    interests: "DevOps, Cloud Infrastructure",
    honorifics: "Mr.",
    gender: "Male",
    birthdate: "1997-02-28",
    citizenship: "USA",
    civil_status: "Single",
    degree_program: "BS Information Technology",
    experience: [
      {
        company: "Cloud Services Group",
        location: "Dallas, TX",
        position: "DevOps Engineer",
        start_date: "2020-10-01",
        end_date: null,
      },
    ],
    affiliations: [
      {
        organization: "Cloud Native Computing Foundation (CNCF)",
        position: "Community Contributor",
        start_date: "2019-07-01",
        end_date: null,
        institution: "University of Texas at Dallas",
      },
    ],
  },
];