export const users = [
    {
      id: "1",
      image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
      username: "emmaj",
      email: "emma.johnson@example.com",
      password: "hashed_pw_1",
      salt: "salt1",
      is_enabled: true,
      first_name: "Emma",
      middle_name: "",
      last_name: "Johnson",
      created_at: "2022-01-01T00:00:00Z",
      deleted_at: null,
      updated_at: "2023-01-01T00:00:00Z",
      role: "alumnus"
    },
    {
      id: "2",
      image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
      username: "liams",
      email: "liam.smith@example.com",
      password: "hashed_pw_2",
      salt: "salt2",
      is_enabled: true,
      first_name: "Liam",
      middle_name: "A.",
      last_name: "Smith",
      created_at: "2021-05-12T00:00:00Z",
      deleted_at: null,
      updated_at: "2023-07-10T00:00:00Z",
      role: "alumnus"
    },
    {
      id: "3",
      image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
      username: "oliviab",
      email: "olivia.brown@example.com",
      password: "hashed_pw_3",
      salt: "salt3",
      is_enabled: true,
      first_name: "Olivia",
      middle_name: "Mae",
      last_name: "Brown",
      created_at: "2020-09-30T00:00:00Z",
      deleted_at: null,
      updated_at: "2022-12-01T00:00:00Z",
      role: "alumnus"
    },
    {
      id: "4",
      image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
      username: "noahd",
      email: "noah.davis@example.com",
      password: "hashed_pw_4",
      salt: "salt4",
      is_enabled: true,
      first_name: "Noah",
      middle_name: "Z.",
      last_name: "Davis",
      created_at: "2019-03-22T00:00:00Z",
      deleted_at: null,
      updated_at: "2023-04-05T00:00:00Z",
      role: "alumnus"
    },
    {
      id: "5",
      image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
      username: "avaw",
      email: "ava.wilson@example.com",
      password: "hashed_pw_5",
      salt: "salt5",
      is_enabled: true,
      first_name: "Ava",
      middle_name: "",
      last_name: "Wilson",
      created_at: "2022-07-01T00:00:00Z",
      deleted_at: null,
      updated_at: "2023-01-15T00:00:00Z",
      role: "alumnus"
    },
    {
      id: "6",
      image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
      username: "william_m",
      email: "william.martinez@example.com",
      password: "hashed_pw_6",
      salt: "salt6",
      is_enabled: true,
      first_name: "William",
      middle_name: "J.",
      last_name: "Martinez",
      created_at: "2018-11-20T00:00:00Z",
      deleted_at: null,
      updated_at: "2024-01-01T00:00:00Z",
      role: "alumnus"
    },
    {
      id: "7",
      image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
      username: "sophiag",
      email: "sophia.garcia@example.com",
      password: "hashed_pw_7",
      salt: "salt7",
      is_enabled: true,
      first_name: "Sophia",
      middle_name: "L.",
      last_name: "Garcia",
      created_at: "2023-01-11T00:00:00Z",
      deleted_at: null,
      updated_at: "2024-04-01T00:00:00Z",
      role: "alumnus"
    },
    {
      id: "8",
      image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
      username: "jamesa",
      email: "james.anderson@example.com",
      password: "hashed_pw_8",
      salt: "salt8",
      is_enabled: true,
      first_name: "James",
      middle_name: "",
      last_name: "Anderson",
      created_at: "2020-06-18T00:00:00Z",
      deleted_at: null,
      updated_at: "2024-01-25T00:00:00Z",
      role: "alumnus"
    },
    {
      id: "9",
      image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
      username: "isabellat",
      email: "isabella.thomas@example.com",
      password: "hashed_pw_9",
      salt: "salt9",
      is_enabled: true,
      first_name: "Isabella",
      middle_name: "Rose",
      last_name: "Thomas",
      created_at: "2021-10-03T00:00:00Z",
      deleted_at: null,
      updated_at: "2024-02-14T00:00:00Z",
      role: "alumnus"
    },
    {
      id: "10",
      image: "https://cdn-icons-png.flaticon.com/512/145/145974.png",
      username: "benl",
      email: "benjamin.lee@example.com",
      password: "hashed_pw_10",
      salt: "salt10",
      is_enabled: true,
      first_name: "Benjamin",
      middle_name: "K.",
      last_name: "Lee",
      created_at: "2017-08-09T00:00:00Z",
      deleted_at: null,
      updated_at: "2024-03-12T00:00:00Z",
      role: "alumnus"
    }
  ]
 
  
  export const alumniProfiles = [
    {
      alum_id: "1",
      birthdate: "1993-06-15",
      location: "New York, NY",
      address: "123 Elm Street",
      gender: "Female",
      sex: 2,
      student_num: "2015-01234",
      citizenship: "American",
      year_graduated: "2015-06-01",
      skills: "Java, Spring Boot, PostgreSQL",
      primary_work_experience_id: "wx-1",
      honorifics: "Ms"
    },
    {
      alum_id: "2",
      birthdate: "1994-09-12",
      location: "San Francisco, CA",
      address: "456 Oak Avenue",
      gender: "Male",
      sex: 1,
      student_num: "2018-04567",
      citizenship: "American",
      year_graduated: "2018-06-01",
      skills: "Python, Scikit-learn, Pandas",
      primary_work_experience_id: "wx-2",
      honorifics: "Mr"
    },
    {
      alum_id: "3",
      birthdate: "1992-04-22",
      location: "Chicago, IL",
      address: "789 Pine Blvd",
      gender: "Female",
      sex: 2,
      student_num: "2012-09876",
      citizenship: "American",
      year_graduated: "2012-06-01",
      skills: "HTML, CSS, JavaScript, Vue.js",
      primary_work_experience_id: "wx-3",
      honorifics: "Ms"
    },
    {
      alum_id: "4",
      birthdate: "1995-11-03",
      location: "Austin, TX",
      address: "123 Main St",
      gender: "Male",
      sex: 1,
      student_num: "2020-07890",
      citizenship: "American",
      year_graduated: "2020-06-01",
      skills: "Docker, Kubernetes, AWS",
      primary_work_experience_id: "wx-4",
      honorifics: "Mr"
    },
    {
      alum_id: "5",
      birthdate: "1993-02-08",
      location: "Seattle, WA",
      address: "908 South Ridge Rd",
      gender: "Female",
      sex: 2,
      student_num: "2017-06543",
      citizenship: "American",
      year_graduated: "2017-06-01",
      skills: "Swift, iOS, Firebase",
      primary_work_experience_id: "wx-5",
      honorifics: "Ms"
    },
    {
      alum_id: "6",
      birthdate: "1990-12-12",
      location: "Miami, FL",
      address: "654 North Park Dr",
      gender: "Male",
      sex: 1,
      student_num: "2014-05555",
      citizenship: "American",
      year_graduated: "2014-06-01",
      skills: "Node.js, React, MongoDB",
      primary_work_experience_id: "wx-6",
      honorifics: "Mr"
    },
    {
      alum_id: "7",
      birthdate: "1991-03-30",
      location: "Denver, CO",
      address: "1122 Windy Ln",
      gender: "Female",
      sex: 2,
      student_num: "2016-04321",
      citizenship: "American",
      year_graduated: "2016-06-01",
      skills: "Azure, Linux, Networking",
      primary_work_experience_id: "wx-7",
      honorifics: "Ms"
    },
    {
      alum_id: "8",
      birthdate: "1989-07-25",
      location: "Boston, MA",
      address: "776 Beacon St",
      gender: "Male",
      sex: 1,
      student_num: "2013-03456",
      citizenship: "American",
      year_graduated: "2013-06-01",
      skills: "OWASP, Pen Testing, Metasploit",
      primary_work_experience_id: "wx-8",
      honorifics: "Mr"
    },
    {
      alum_id: "9",
      birthdate: "1996-10-19",
      location: "Los Angeles, CA",
      address: "559 West Side Ave",
      gender: "Female",
      sex: 2,
      student_num: "2019-06789",
      citizenship: "American",
      year_graduated: "2019-06-01",
      skills: "PyTorch, Deep Learning, NLP",
      primary_work_experience_id: "wx-9",
      honorifics: "Ms"
    },
    {
      alum_id: "10",
      birthdate: "1991-01-01",
      location: "Atlanta, GA",
      address: "889 City Center Dr",
      gender: "Male",
      sex: 1,
      student_num: "2011-02222",
      citizenship: "American",
      year_graduated: "2011-06-01",
      skills: "SQL, Oracle, PL/SQL",
      primary_work_experience_id: "wx-10",
      honorifics: "Mr"
    }
  ];
  