// mockData.js
const fundraisersData = [
  {
    id: "1",
    title: "Women in Tech Scholarship",
    type: "Scholarship",
    image: "/projects/assets/Donation.jpg",
    status: "approved",
    description: "Supporting female students pursuing degrees in CS and IT to increase representation in tech.",
    goal: "₱300,000",
    raised: "₱200,000",
    donors: 87,
    endDate: "2025-09-30",
    createdAt: "2025-01-15",
    rejectionReason: null,
    messages: [
      {
        id: "m1",
        sender: "Admin",
        content: "Your fundraiser has been approved! Congratulations!",
        timestamp: "2025-01-16T10:30:00",
        isRead: true,
      },
      {
        id: "m2",
        sender: "Admin",
        content: "We've featured your fundraiser on our homepage.",
        timestamp: "2025-01-20T14:22:00",
        isRead: false,
      },
    ],
  },
  {
    id: "2",
    title: "Community Library Expansion",
    type: "Community",
    image: "/projects/assets/Library.jpg",
    status: "pending",
    description: "Expanding our local library to provide more educational resources to the community.",
    goal: "₱500,000",
    raised: "₱0",
    donors: 0,
    endDate: "2025-10-15",
    createdAt: "2025-04-28",
    rejectionReason: null,
    messages: [],
  },
  {
    id: "3",
    title: "Medical Support for Children",
    type: "Medical",
    image: "/projects/assets/Medical.jpg",
    status: "rejected",
    description: "Providing medical support and treatment for children with rare diseases.",
    goal: "₱1,000,000",
    raised: "₱0",
    donors: 0,
    endDate: "2025-12-31",
    createdAt: "2025-04-20",
    rejectionReason: {
      mainReason: "Incomplete Documentation",
      details: "Your fundraiser request was rejected due to missing documentation. Please provide the following documents: 1) Medical certificates, 2) Hospital affiliation letter, 3) Detailed cost breakdown.",
      resubmissionGuidelines: "You can resubmit your fundraiser after completing the required documentation. Make sure to address all the points mentioned in the rejection reason."
    },
    messages: [
      {
        id: "m3",
        sender: "Admin",
        content: "We need additional documentation for your fundraiser request.",
        timestamp: "2025-04-22T09:15:00",
        isRead: true,
      },
      {
        id: "m4",
        sender: "Admin",
        content: "Your fundraiser has been rejected due to incomplete documentation.",
        timestamp: "2025-04-24T16:45:00",
        isRead: true,
      },
    ],
  },
  {
    id: "4",
    title: "Animal Shelter Renovation",
    type: "Animal Welfare",
    image: "/projects/assets/Animal.jpg",
    status: "approved",
    description: "Renovating our local animal shelter to provide better conditions for rescued animals.",
    goal: "₱250,000",
    raised: "₱75,000",
    donors: 32,
    endDate: "2025-08-15",
    createdAt: "2025-03-10",
    rejectionReason: null,
    messages: [
      {
        id: "m5",
        sender: "Admin",
        content: "Your fundraiser has been approved!",
        timestamp: "2025-03-12T11:20:00",
        isRead: true,
      },
      {
        id: "m6",
        sender: "Donor",
        content: "I'd like to know more about how the funds will be used for renovation.",
        timestamp: "2025-04-05T15:30:00",
        isRead: false,
      },
    ],
  },
];

export default fundraisersData;