export const DONATION_MODE_OF_PAYMENT = {
  PHYSICAL_PAYMENT: 0,
  BANK_TRANSFER: 1,
};

export const DONATION_MODE_OF_PAYMENT_LABELS = {
  [DONATION_MODE_OF_PAYMENT.PHYSICAL_PAYMENT]: "Physical",
  [DONATION_MODE_OF_PAYMENT.BANK_TRANSFER]: "Bank Transfer",
};