export const REQUEST_STATUS = {
  SENT: 0,
  APPROVED: 1,
  REJECTED: 2,
};

export const REQUEST_STATUS_LABELS = {
  [REQUEST_STATUS.SENT]: "Sent",
  [REQUEST_STATUS.APPROVED]: "Approved",
  [REQUEST_STATUS.REJECTED]: "Rejected",
};