// app/admin/events/eventDummy.js

const eventList = [
  {
    id: 1,
    event_name: 'Alumni Homecoming',
    location: 'ICS',
    type: 'In-Person',
    date: 'April 1, 2025',
    going: 80,
    interested: 20,
  },
  {
    id: 2,
    event_name: 'Tech Conference 2025',
    location: 'Auditorium',
    type: 'In-Person',
    date: 'May 15, 2025',
    going: 120,
    interested: 45,
  },
  {
    id: 3,
    event_name: 'Virtual Networking',
    location: 'Online',
    type: 'Online',
    date: 'June 5, 2025',
    going: 90,
    interested: 30,
  },
  {
    id: 4,
    event_name: 'Startup Pitch Night',
    location: 'Business Center',
    type: 'In-Person',
    date: 'July 10, 2025',
    going: 50,
    interested: 15,
  },
  {
    id: 5,
    event_name: 'Career Fair',
    location: 'Main Hall',
    type: 'In-Person',
    date: 'August 20, 2025',
    going: 200,
    interested: 70,
  },
  {
    id: 6,
    event_name: 'Coding Bootcamp',
    location: 'Online',
    type: 'Online',
    date: 'September 3, 2025',
    going: 150,
    interested: 60,
  },
  {
    id: 7,
    event_name: 'Entrepreneurship Workshop',
    location: 'Business Center',
    type: 'In-Person',
    date: 'October 12, 2025',
    going: 75,
    interested: 25,
  },
  {
    id: 8,
    event_name: 'Alumni Panel Talk',
    location: 'Conference Room B',
    type: 'In-Person',
    date: 'November 5, 2025',
    going: 95,
    interested: 40,
  },
  {
    id: 9,
    event_name: 'Holiday Mixer',
    location: 'ICS',
    type: 'In-Person',
    date: 'December 18, 2025',
    going: 130,
    interested: 50,
  },
  {
    id: 10,
    event_name: 'Web Dev Summit',
    location: 'Auditorium',
    type: 'In-Person',
    date: 'January 20, 2026',
    going: 180,
    interested: 90,
  },
  {
    id: 11,
    event_name: 'AI and Data Science Conference',
    location: 'Online',
    type: 'Online',
    date: 'February 14, 2026',
    going: 210,
    interested: 110,
  },
  {
    id: 12,
    event_name: 'Blockchain Expo',
    location: 'Business Center',
    type: 'In-Person',
    date: 'March 5, 2026',
    going: 160,
    interested: 70,
  },
];

export default eventList;
